language: node_js
node_js:
    - "12"

notifications:
  email:
    on_success: never
    on_failure: always

install:
    - npm install

cache:
  directories:
    - node_modules

script:
  - npm run generate
  - npm run generate-api-docs
